spring:
  config:
    import: "aws-parameterstore:/dropp/prod/"
  datasource:
    url: ${mysql-restaurant-url}
    username: ${mysql-user}
    password: ${mysql-pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: ${eureka-url}